name: build-release-deploy
on:
  workflow_dispatch:
    branches:
      - main
  push:
    tags: ["v*"]

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the rep

env:
  ECR_PUBLIC_URL: public.ecr.aws/mailprotector
  ECR_REPOSITORY: rspamd

jobs:
  build-release:
    name: Build Docker image and push to ECR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-region: [us-east-1]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: config-aws-region
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PRODUCTION_IAM_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo "image_tag=${TAG}" >> $GITHUB_ENV
          echo "latest_tag=latest" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Amazon Public ECR ${{ matrix.aws-region }}
        id: login-ecr
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Build image for ${{ matrix.aws-region }}
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Tag and Push image to AWS ECR ${{ matrix.aws-region }} as SHA
        env:
          ECR_URL: ${{ env.ECR_PUBLIC_URL}}/${{ env.ECR_REPOSITORY }}:${{ env.image_tag }}
        run: |
          docker tag ${{ env.image_tag }} ${{ env.ECR_URL }}
          docker push ${{ env.ECR_URL }}

      - name: Tag and Push image to AWS ECR ${{ matrix.aws-region }} as latest
        env:
          ECR_URL: ${{ env.ECR_PUBLIC_URL}}/${{ env.ECR_REPOSITORY }}:${{ env.latest_tag }}
        run: |
          docker tag ${{ env.image_tag }} ${{ env.ECR_URL }}
          docker push ${{ env.ECR_URL }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache/
          mv /tmp/.buildx-cache-new/ /tmp/.buildx-cache/
